sonar.projectKey=leanmaga_PolleriaPatagonia
sonar.organization=leanmaga

# Información del proyecto
sonar.projectName=PolleriaPatagonia
sonar.projectVersion=1.0

# Carpetas a analizar (típico para React)
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

# Exclusiones importantes para React
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/public/**,**/*.test.js,**/*.test.jsx

# Configuración para JavaScript/React
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8